### PR TITLE
Make editor default to spaces as indentation, not tabs; Update code-input to v2.1.0

### PR DESCRIPTION
**Pull request by WebCoder49**
I have added these changes to update my `code-input` library in your code from version 2.0.1 to version 2.1.0, because of its added support for spaces rather than tabs as [indentation](https://en.wikipedia.org/wiki/Indentation_(typesetting)#Indentation_in_programming), and have changed 2 lines of your JavaScript code to use this feature, as well as forcing the CSS placeholder colour to match your old code.

The reason is that most people use spaces for indentation and the `code-input` old default behaviour of using tabs meant the `Indent` plugin didn't fully work with code copied from other sources like the internet. As you can see below, the change is not very visible but does affect how `Shift+Tab` unindenting and auto-indenting when `Enter` is pressed works, and Visual Studio code shows the difference under the red circles.
| Tabs as indentation - your older code | Spaces as indentation - the code in this pull request |
|---|---|
| image | image |

### CODE REVIEW

**Comment by WebCoder49** [comment]
@vcdomith , please merge this pull request to add it to your own code if it is useful or let me know if you have any queries.

**Comment by vcdomith** [comment]
Thanks for your kind input! Tomorrow I'll take a look at it and merge.

**Comment by WebCoder49** [comment]
I seem to have merged your changes wrong. Please don't merge it until I have added my addition to your latest changes properly

**Comment by WebCoder49** [comment]
By the way, my time zone is UTC (United Kingdom time).

**Comment by WebCoder49** [comment]
You should be able to merge this now, @vcdomith - I have updated it to include your latest changes. 

Additionally, relating to your use of code-input, I have a few suggestions:
1. I think you might want to make the `code-input` have the disabled attribute when viewing posts so it can't be edited.
```javascript
// Add after line 87 of criaPostLi.js
codeInput.setAttribute('disabled', true)
```
2. You may want to find a similar way to avoid posts being edited when being viewed on the "Editor de Códigos | Post Detalhado" page but it's up to you.
3. For non-editable post views (but not for the editor), I would recommend using just the `<pre><code>` element and not the `<code-input>` element as it means less time is spent loading `code-input` unnecessarily - points 1 and 2 would no longer be needed if you did this, but the CSS styles of ...`code-input pre code`... would need to be changed to ...`pre code`..., removing the `code-input` part.

Thank you again for choosing my library and good luck in your project - you are definitely making progress quickly.

**Comment by vcdomith** [comment]
Merged it now. Sorry for the delay, I had a bit on my hand... Thanks for your kind work, this means a lot!

**Pull request merged**
